config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :procedures, only: [:index, :show] do
    post 'search/', to: 'procedures#search', on: :collection
    get 'search/', to: 'procedures#index', on: :collection
    get 'export/', to: 'procedures#export', on: :collection
    post 'print/', to: 'procedures#print', on: :collection
  end

  resources :health_facilities, only: [:show]

  resources :general_data, only: [:index] do
    post 'print/', to: 'general_data#print', on: :collection
  end
end

app/views/shared/_footer.html.erb
<footer class="py-3 bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-6">
        <p class="m-0 text-left text-white small">
          <strong>
            <%= t('views.shared.footer.sms') %>
          </strong>
        </p>
        <p class="m-0 text-left text-white small">
          R. General Jardim, 36 - Vila Buarque
        </p>
        <p class="m-0 text-left text-white small">
          <abbr title="<%= t('views.shared.footer.telephone') %>">
            <%= t('views.shared.footer.telephone')[0] %>:
          </abbr>
          (11) 3397-2000
        </p>
      </div>
      <div class="col-lg-4 col-sm-6">
        <p class="m-0 text-left text-white small">
          <strong>
            <%= t('views.shared.footer.contact') %>
          </strong>
        </p>
        <p class="m-0 text-left text-white small">
          ouvidoriasaude@prefeitura.sp.gov.br
        </p>
        <p class="m-0 text-left text-white small">
          <abbr title="<%= t('views.shared.footer.telephone') %>">
            <%= t('views.shared.footer.telephone')[0] %>:
          </abbr>
          156
        </p>
      </div>
      <!--
      <div class="col-lg-4 col-sm-6">
        <ul class="footer-links small">
          <li>
            <%= link_to t('views.shared.footer.about'), '#', class: 'link' %>
          </li>
          <li>
            <%= link_to t('views.shared.footer.faq'), '#', class: 'link' %>
          </li>
        </ul>
      </div>
      -->
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= image_tag 'partner-logo.png', class: 'partner-logo' %>

    <%= link_to t('views.shared.header.application_name'), root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to t('views.shared.header.advanced_search'), procedures_path, class: 'nav-link', data: { turbolinks: false } %>
        </li>

        <!-- FIXME: implement this page
        <li class="nav-item">
          <%= link_to t('views.shared.header.health_facilities'), '#', class: 'nav-link' %>
        </li>
        -->

        <li class="nav-item">
          <%= link_to t('views.shared.header.general_data'), general_data_path, class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('views.shared.header.user') %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
            <% if user_signed_in? %>
              <% if current_user.admin %>
                <%= link_to t('views.shared.header.admin'), trestle.root_path, class: 'dropdown-item' %>
              <% end %>
              <%= link_to t('views.shared.header.logout'), destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            <% else %>
              <%= link_to t('views.shared.header.login'), new_user_session_path, class: 'dropdown-item' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>