config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :procedures, only: [:index, :show] do
    post 'search/', to: 'procedures#search', on: :collection
    get 'search/', to: 'procedures#index', on: :collection
    get 'export/', to: 'procedures#export', on: :collection
    post 'print/', to: 'procedures#print', on: :collection
  end

  resources :health_facilities, only: [:show]

  resources :general_data, only: [:index] do
    post 'print/', to: 'general_data#print', on: :collection
  end
end

app/controllers/procedures_controller.rb
# frozen_string_literal: true

class ProceduresController < ApplicationController
  include RansackMemory::Concern
  include ProceduresSearchConcern

  before_action :set_administrative_entities, only: %i[index search print]
  before_action :save_and_load_filters, only: %i[search export print]
  before_action :set_search_results, only: %i[index search export print]

  def index
    @census_sectors_counts = {}
  end

  def search
    census_sectors_procedures_counter = CensusSectorsProceduresCounterService.new(@procedures_ids)
    csw_heat_map_params.each do |filter, value|
      census_sectors_procedures_counter.set_filter(filter.to_sym, value == 'true')
    end
    @census_sectors_counts = census_sectors_procedures_counter.counts

    render 'index'
  end

  def show
    @patient_datum = PatientDatum
                     .includes(
                       :administrative_sector, :subprefecture, :technical_health_supervision,
                       :regional_health_coordination, :census_sector
                     )
                     .find_by!(procedure_id: params[:id])

    @hospitalization_datum = HospitalizationDatum
                             .includes(:icd_category)
                             .find_by!(procedure_id: params[:id])

    render layout: false
  end

  def export
    @patients_data = PatientDatum.includes(
      { hospitalization_datum: %i[health_facility icd_subcategory secondary_icd1 secondary_icd2] },
      :administrative_sector,
      :subprefecture,
      :technical_health_supervision,
      :regional_health_coordination
    ).where(procedure_id: @procedures_ids)
  end

  def print
    @base64_map = print_params[:map_image]

    render pdf: 'procedures', orientation: 'Landscape', page_size: 'A4', layout: 'wicked_pdf'
  end

  private

  def set_administrative_entities
    @cities = City.all
    @census_sectors = CensusSector.all
    @regional_health_coordinations = RegionalHealthCoordination.all
    @technical_health_supervisions = TechnicalHealthSupervision.all
    @subprefectures = Subprefecture.all
    @administrative_sectors = AdministrativeSector.all
    @ubs = Ubs.all
    @fhs = FamilyHealthStrategy.all
  end

  def csw_heat_map_params
    params.fetch(:csw_heat_map).permit(CensusSectorsProceduresCounterService::ALL_FILTERS)
  end

  def print_params
    params.permit(:map_image)
  end
end

app/helpers/procedures_helper.rb
# frozen_string_literal: true

module ProceduresHelper
  def model_icd_options(model_class)
    model_class
      .distinct
      .where.not(code: nil)
      .order(:code)
      .pluck(:code, :id, :description)
      .map do |option|
        formated_option = option.clone
        formated_option[0] = option[0] + ' - ' + option[2].titleize
        formated_option[0..1]
      end
  end

  def icd_category_options
    model_icd_options(IcdCategory)
  end

  def icd_subcategory_options
    model_icd_options(IcdSubcategory)
  end

  def model_number_attribute_options(model_class, attribute)
    model_class
      .distinct
      .where
      .not(attribute => nil)
      .order(attribute)
      .pluck(attribute)
  end

  def hospitalization_type_options
    model_number_attribute_options(HospitalizationDatum, :hospitalization_type)
  end

  def complexity_options
    model_number_attribute_options(HospitalizationDatum, :complexity)
  end

  def specialty_options
    model_number_attribute_options(HospitalizationDatum, :specialty)
  end

  def competence_options
    model_number_attribute_options(HospitalizationDatum, :competence)
  end

  def hospitalization_group_options
    model_number_attribute_options(HospitalizationDatum, :hospitalization_group)
  end

  def financing_options
    model_number_attribute_options(HospitalizationDatum, :financing)
  end

  def max_hospitalization_days
    HospitalizationDatum.maximum(:hospitalization_days)
  end

  def max_hospitalization_rates
    HospitalizationDatum.maximum(:hospitalization_rates)
  end

  def max_uti_rates
    HospitalizationDatum.maximum(:uti_rates)
  end

  def max_ui_rates
    HospitalizationDatum.maximum(:ui_rates)
  end

  def max_service_value
    HospitalizationDatum.maximum(:service_value)
  end

  def max_distance
    HospitalizationDatum.maximum(:distance)
  end
end

app/views/procedures/map/_health_facility.js.erb
proceduresMap.addHealthFacility(
  '<%= image_url("#{health_facility.administration}_hf_icon.png") %>',
  <%= health_facility.latitude %>,
  <%= health_facility.longitude %>,
  '<%= health_facility_path(health_facility.id) %>',
  `<%= t '.error' %>`
);

<% distance_percentiles(health_facility).each do |percentile, distance| %>
  proceduresMap.addHealthFacilityPercentile(
    <%= health_facility.latitude %>,
    <%= health_facility.longitude %>,
    <%= percentile %>,
    <%= distance %>,
    [
      '<%= t '.percentile' %>',
      '<%= t '.radius' %>'
    ]
  );
<% end %>

app/views/procedures/map/_legend.html.erb
<h5 class="pt-4"><%= t '.title' %></h5>

<div class="container">
  <div class="row align-items-center justify-content-start">
    <div class="col-2">
      <%= image_tag 'ESTADUAL_hf_icon.png' %>
    </div>

    <div class="col-4 align-self-center pl-0">
      <%= t '.state' %>
    </div>

    <div class="col-2">
      <%= image_tag 'MUNICIPAL_hf_icon.png' %>
    </div>

    <div class="col-4 align-self-center pl-0">
      <%= t '.city' %>
    </div>
  </div>
</div>

app/views/procedures/map/_limits_feature.js.erb
limitsFeatures.addFeature('<%= object.class.to_s %>', '<%= object.name %>', <%= object.shape.html_safe %>);

app/views/procedures/map/_load.js.erb
<%= javascript_pack_tag 'procedures_map/ProceduresMap' %>
<%= javascript_pack_tag 'procedures_map/LimitsFeatures' %>
<%= javascript_pack_tag 'procedures_map/LoadingOverlay' %>

<%= javascript_tag do %>
  var proceduresMap = new ProceduresMap('map', L, $, <%= dataset_proportion %>);
  var limitsFeatures = new LimitsFeatures();

  var loadingOverlay = new LoadingOverlay($);

  window.onload = function() {
    proceduresMap.invalidateSize();

    <%= render partial: 'procedures/map/health_facility.js', collection: health_facilities, cached: true %>

    <% patients_data.find_in_batches do |patients_data_batch| %>
      <%= render partial: 'procedures/map/patient_data.js', collection: patients_data_batch, cached: true %>
    <% end %>

    proceduresMap.applyPatientCluster();
    proceduresMap.toggleCluster();
    proceduresMap.toggleHealthFacilities();

    <% census_sectors_counts.each do |census_sector, counts| %>
      proceduresMap.createCSWHMarker(<%= census_sector.latitude %>, <%= census_sector.longitude %>, <%= counts[:rate] %>);
    <% end %>

    <%= render partial: 'procedures/map/limits_feature.js', collection: cities, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= City.to_s %>', limitsFeatures.getFeatureCollection('<%= City.to_s %>'));

    <% census_sectors.find_in_batches do |census_sectors_batch| %>
      <%= render partial: 'procedures/map/limits_feature.js', collection: census_sectors_batch, as: :object, cached: true %>
    <% end %>
    proceduresMap.buildLimitsLayer('<%= CensusSector.to_s %>', limitsFeatures.getFeatureCollection('<%= CensusSector.to_s %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: regional_health_coordinations, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= RegionalHealthCoordination %>', limitsFeatures.getFeatureCollection('<%= RegionalHealthCoordination %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: technical_health_supervisions, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= TechnicalHealthSupervision %>', limitsFeatures.getFeatureCollection('<%= TechnicalHealthSupervision %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: subprefectures, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= Subprefecture %>', limitsFeatures.getFeatureCollection('<%= Subprefecture %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: administrative_sectors, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= AdministrativeSector %>', limitsFeatures.getFeatureCollection('<%= AdministrativeSector %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: ubs, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= Ubs %>', limitsFeatures.getFeatureCollection('<%= Ubs %>'));

    <%= render partial: 'procedures/map/limits_feature.js', collection: fhs, as: :object, cached: true %>
    proceduresMap.buildLimitsLayer('<%= FamilyHealthStrategy %>', limitsFeatures.getFeatureCollection('<%= FamilyHealthStrategy %>'));
  };
<% end %>

app/views/procedures/map/_options.html.erb
<div class="accordion" id="map-options-accordion">
  <div class="card">
    <div class="card-header" id="headingMapOptionsOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseMapOptionsOne" aria-expanded="true" aria-controls="collapseMapOptionsOne">
          <%= t '.clustering' %>
        </button>
      </h5>
    </div>

    <div id="collapseMapOptionsOne" class="collapse" aria-labelledby="headingMapOptionsOne" data-parent="#map-options-accordion">
      <div class="card-body">
        <div class="form-check">
          <%= check_box_tag(:clustering_enabled, true, true, class: 'form-check-input', onchange: 'proceduresMap.toggleCluster()') %>
          <%= label_tag(:clustering_enabled, t('.enabled'), class: 'form-check-label') %>
        </div>

        <hr>

        <div id="clustering_radius_container">
          <%= label_tag(:clustering_radius, t('.radius')) %><br>
          <%= text_field_tag(:clustering_radius, nil,
                             data: {
                               provide: 'slider',
                               slider_min: 0,
                               slider_max: 10,
                               slider_step: 0.1,
                               slider_tooltip: 'show'
                             }) %>
        </div>
      </div>
      <script>
        $('#clustering_radius').slider().on('slideStop', function(slider) {
          proceduresMap.clusterRadiusEvent(slider)
        })
      </script>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingMapOptionsTwo">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseMapOptionsTwo" aria-expanded="true" aria-controls="collapseMapOptionsTwo">
          <%= t '.heat_map' %>
        </button>
      </h5>
    </div>

    <div id="collapseMapOptionsTwo" class="collapse" aria-labelledby="headingMapOptionsTwo" data-parent="#map-options-accordion">
      <div class="card-body">
        <div class="form-check">
          <%= check_box_tag(:heat_map_enabled, true, false, class: 'form-check-input', onchange: 'proceduresMap.toggleHeatmap()') %>
          <%= label_tag(:heat_map_enabled, t('.count_heat_map'), class: 'form-check-label') %>
        </div>

        <hr>

        <%= label_tag(:heat_map_radius, t('.radius')) %><br>
        <%= text_field_tag(:heat_map_radius, 25,
                           data: {
                             provide: 'slider',
                             slider_min: 0,
                             slider_max: 10,
                             slider_step: 0.1,
                             slider_tooltip: 'show'
                          },
                          onchange: 'proceduresMap.heatmapRadiusEvent(this)') %>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:heat_map_high_contrast, true, false, class: 'form-check-input', onchange: 'proceduresMap.toggleHeatmapHighContrast()') %>
          <%= label_tag(:heat_map_high_contrast, t('.high_contrast'), class: 'form-check-label') %>
        </div>

        <hr>

        <%= label_tag(:heat_map_opacity, t('.opacity')) %><br>
        <%= text_field_tag(:heat_map_opacity, nil,
                           data: {
                             provide: 'slider',
                             slider_min: 0,
                             slider_max: 1,
                             slider_step: 0.05,
                             slider_tooltip: 'show'
                          },
                          onchange: 'proceduresMap.heatmapOpacityEvent(this)') %>

        <div class="form-check">
          <%= check_box_tag(:csw_heat_map_enabled, true, false, class: 'form-check-input', onchange: 'proceduresMap.toggleCSWHeatmap()') %>
          <%= label_tag(:csw_heat_map_enabled, t('.csw_heat_map'), class: 'form-check-label') %>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingMapOptionsThree">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseMapOptionsThree" aria-expanded="true" aria-controls="collapseMapOptionsThree">
          <%= t '.administrative_limits' %>
        </button>
      </h5>
    </div>

    <div id="collapseMapOptionsThree" class="collapse" aria-labelledby="headingMapOptionsThree" data-parent="#map-options-accordion">
      <div class="card-body">
        <div class="form-check">
          <%= check_box_tag(:show_city_limits, true, false, class: 'form-check-input',
                            onchange: "proceduresMap.toggleLimits('#{City}')") %>
          <%= label_tag(:show_city_limits, t('.city'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_rhc_limits, true, false, class: 'form-check-input', onchange: "proceduresMap.toggleLimits('#{RegionalHealthCoordination}')") %>
          <%= label_tag(:show_rhc_limits, t('.regional_health_coordination'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_ths_limits, true, false, class: 'form-check-input', onchange: "proceduresMap.toggleLimits('#{TechnicalHealthSupervision}')") %>
          <%= label_tag(:show_ths_limits, t('.technical_health_supervision'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_subprefecture_limits, true, false, class: 'form-check-input', onchange: "proceduresMap.toggleLimits('#{Subprefecture}')") %>
          <%= label_tag(:show_subprefecture_limits, t('.subprefecture'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_administrative_sectors_limits, true, false, class: 'form-check-input', onchange: "proceduresMap.toggleLimits('#{AdministrativeSector}')") %>
          <%= label_tag(:show_administrative_sectors_limits, t('.administrative_sector'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_ubs_limits, true, false, class: 'form-check-input',
                            onchange: "proceduresMap.toggleLimits('#{Ubs}')") %>
          <%= label_tag(:show_ubs_limits, t('.ubs'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_fhs_limits, true, false, class: 'form-check-input',
                            onchange: "proceduresMap.toggleLimits('#{FamilyHealthStrategy}')") %>
          <%= label_tag(:show_fhs_limits, t('.fhs'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:show_cs_limits, true, false, class: 'form-check-input', onchange: "proceduresMap.toggleLimits('#{CensusSector}')") %>
          <%= label_tag(:show_cs_limits, t('.census_sectors'), class: 'form-check-label') %>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingMapOptionsFour">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseMapOptionsFour" aria-expanded="true" aria-controls="collapseMapOptionsFour">
          <%= t '.health_facilities' %>
        </button>
      </h5>
    </div>

    <div id="collapseMapOptionsFour" class="collapse" aria-labelledby="headingMapOptionsFour" data-parent="#map-options-accordion">
      <div class="card-body">
        <div class="form-check">
          <%= check_box_tag(:health_facilities_enabled, true, true, class: 'form-check-input', onchange: 'proceduresMap.toggleHealthFacilities()') %>
          <%= label_tag(:health_facilities_enabled, t('.enabled'), class: 'form-check-label') %>
        </div>

        <hr>

        <div class="form-check">
          <%= check_box_tag(:health_facilities_percentiles_enabled, true, false, class: 'form-check-input', onchange: 'proceduresMap.toggleHealthFacilitiesPercentiles()') %>
          <%= label_tag(:health_facilities_percentiles_enabled, t('.percentiles_enabled'), class: 'form-check-label') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/procedures/map/_patient_data.js.erb
proceduresMap.createPatientDataMarker(<%= "#{patient_data.latitude}, #{patient_data.longitude}, '#{procedure_path(patient_data.procedure_id)}'".html_safe %>, `<%= t '.error' %>`);