config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :procedures, only: [:index, :show] do
    post 'search/', to: 'procedures#search', on: :collection
    get 'search/', to: 'procedures#index', on: :collection
    get 'export/', to: 'procedures#export', on: :collection
    post 'print/', to: 'procedures#print', on: :collection
  end

  resources :health_facilities, only: [:show]

  resources :general_data, only: [:index] do
    post 'print/', to: 'general_data#print', on: :collection
  end
end

app/controllers/procedures_controller.rb
# frozen_string_literal: true

class ProceduresController < ApplicationController
  include RansackMemory::Concern
  include ProceduresSearchConcern

  before_action :set_administrative_entities, only: %i[index search print]
  before_action :save_and_load_filters, only: %i[search export print]
  before_action :set_search_results, only: %i[index search export print]

  def index
    @census_sectors_counts = {}
  end

  def search
    census_sectors_procedures_counter = CensusSectorsProceduresCounterService.new(@procedures_ids)
    csw_heat_map_params.each do |filter, value|
      census_sectors_procedures_counter.set_filter(filter.to_sym, value == 'true')
    end
    @census_sectors_counts = census_sectors_procedures_counter.counts

    render 'index'
  end

  def show
    @patient_datum = PatientDatum
                     .includes(
                       :administrative_sector, :subprefecture, :technical_health_supervision,
                       :regional_health_coordination, :census_sector
                     )
                     .find_by!(procedure_id: params[:id])

    @hospitalization_datum = HospitalizationDatum
                             .includes(:icd_category)
                             .find_by!(procedure_id: params[:id])

    render layout: false
  end

  def export
    @patients_data = PatientDatum.includes(
      { hospitalization_datum: %i[health_facility icd_subcategory secondary_icd1 secondary_icd2] },
      :administrative_sector,
      :subprefecture,
      :technical_health_supervision,
      :regional_health_coordination
    ).where(procedure_id: @procedures_ids)
  end

  def print
    @base64_map = print_params[:map_image]

    render pdf: 'procedures', orientation: 'Landscape', page_size: 'A4', layout: 'wicked_pdf'
  end

  private

  def set_administrative_entities
    @cities = City.all
    @census_sectors = CensusSector.all
    @regional_health_coordinations = RegionalHealthCoordination.all
    @technical_health_supervisions = TechnicalHealthSupervision.all
    @subprefectures = Subprefecture.all
    @administrative_sectors = AdministrativeSector.all
    @ubs = Ubs.all
    @fhs = FamilyHealthStrategy.all
  end

  def csw_heat_map_params
    params.fetch(:csw_heat_map).permit(CensusSectorsProceduresCounterService::ALL_FILTERS)
  end

  def print_params
    params.permit(:map_image)
  end
end

app/helpers/procedures_helper.rb
# frozen_string_literal: true

module ProceduresHelper
  def model_icd_options(model_class)
    model_class
      .distinct
      .where.not(code: nil)
      .order(:code)
      .pluck(:code, :id, :description)
      .map do |option|
        formated_option = option.clone
        formated_option[0] = option[0] + ' - ' + option[2].titleize
        formated_option[0..1]
      end
  end

  def icd_category_options
    model_icd_options(IcdCategory)
  end

  def icd_subcategory_options
    model_icd_options(IcdSubcategory)
  end

  def model_number_attribute_options(model_class, attribute)
    model_class
      .distinct
      .where
      .not(attribute => nil)
      .order(attribute)
      .pluck(attribute)
  end

  def hospitalization_type_options
    model_number_attribute_options(HospitalizationDatum, :hospitalization_type)
  end

  def complexity_options
    model_number_attribute_options(HospitalizationDatum, :complexity)
  end

  def specialty_options
    model_number_attribute_options(HospitalizationDatum, :specialty)
  end

  def competence_options
    model_number_attribute_options(HospitalizationDatum, :competence)
  end

  def hospitalization_group_options
    model_number_attribute_options(HospitalizationDatum, :hospitalization_group)
  end

  def financing_options
    model_number_attribute_options(HospitalizationDatum, :financing)
  end

  def max_hospitalization_days
    HospitalizationDatum.maximum(:hospitalization_days)
  end

  def max_hospitalization_rates
    HospitalizationDatum.maximum(:hospitalization_rates)
  end

  def max_uti_rates
    HospitalizationDatum.maximum(:uti_rates)
  end

  def max_ui_rates
    HospitalizationDatum.maximum(:ui_rates)
  end

  def max_service_value
    HospitalizationDatum.maximum(:service_value)
  end

  def max_distance
    HospitalizationDatum.maximum(:distance)
  end
end

app/views/procedures/_pdf_generator.html.erb
<%= javascript_pack_tag 'procedures_map/ImageGenerator' %>

<%= form_with url: print_procedures_path, id: 'image_form' do %>
  <%= hidden_field_tag :map_image  %>
<% end %>

<%= javascript_tag do %>
  imageGenerator = new ImageGenerator(html2canvas, $, 'image_form', 'map_image');
<% end %>

<%= link_to t('.pdf'), 'javascript:;', class: 'm-2 btn btn-secondary overlay-button', onclick: "imageGenerator.generate('map')" %>

app/views/procedures/_procedure.csv.erb
<%= [
  patient_data.procedure_id,
  patient_data.latitude,
  patient_data.longitude,
  patient_data.gender,
  patient_data.age_year,
  patient_data.race,
  patient_data.educational_level,
  patient_data.hospitalization_datum.health_facility.cnes,
  patient_data.hospitalization_datum.gestor_id,
  patient_data.hospitalization_datum.hospitalization_type,
  patient_data.hospitalization_datum.competence,
  patient_data.hospitalization_datum.issue_date,
  patient_data.hospitalization_datum.admission_date,
  patient_data.hospitalization_datum.leave_date,
  patient_data.hospitalization_datum.complexity,
  patient_data.hospitalization_datum.hospitalization_group,
  patient_data.hospitalization_datum.icd_subcategory.code,
  patient_data.hospitalization_datum.secondary_icd1 ? patient_data.hospitalization_datum.secondary_icd1.code : nil,
  patient_data.hospitalization_datum.secondary_icd2 ? patient_data.hospitalization_datum.secondary_icd2.code : nil,
  patient_data.hospitalization_datum.hospitalization_rates,
  patient_data.hospitalization_datum.uti_rates,
  patient_data.hospitalization_datum.uti_rates,
  patient_data.hospitalization_datum.hospitalization_days,
  patient_data.hospitalization_datum.financing,
  patient_data.hospitalization_datum.service_value,
  patient_data.administrative_sector.name,
  patient_data.subprefecture.name,
  patient_data.technical_health_supervision.name,
  patient_data.regional_health_coordination.name,
  patient_data.hospitalization_datum.distance
].join(';') %>

app/views/procedures/export.csv.erb
COD;LAT_SC;LONG_SC;P_SEXO;P_IDADE;P_RACA;LV_INSTRU;CNES;GESTOR_ID;CAR_INTEN;CMPT;DT_EMISSAO;DT_INTERNA;DT_SAIDA;COMPLEXIDA;PROC_RE;DIAG_PR;DIAG_SE1;DIAG_SE2;DIARIAS;DIARIAS_UT;DIARIAS_UI;DIAS_PERM;FINANC;VAL_TOT;DA;SUB;STS;CRS;DISTANCIA_KM
<% @patients_data.find_in_batches do |patients_data_batch| %>
  <%= render partial: 'procedures/procedure.csv', collection: patients_data_batch, as: :patient_data, cached: true %>
<% end %>

app/views/procedures/index.html.erb
<div class="container-fluid px-0 h-100">
  <div class="row no-gutters h-100">
    <div id="map" class="col-md-8"></div>

    <div class="filters col-md-4 py-4 px-4">
      <h5><%= t('.filters') %></h5>

      <div id="filters-accordion">
        <%= search_form_for @search, url: search_procedures_path, html: { method: :post } do |f| %>
          <%= render partial: 'procedures/filters/health_facilities', locals: { form: f } %>

          <%= render partial: 'procedures/filters/procedures', locals: { form: f } %>

          <%= render partial: 'procedures/filters/patients', locals: { form: f } %>

          <%= render partial: 'procedures/filters/csw_heat_map' %>

          <%= submit_tag(t('.search'), class: 'm-2 btn btn-primary overlay-button') %>

          <!-- TODO: load search values to form fields then add the = below
          <% clear_filter title: t('.clear_filters'), class: 'm-2 btn btn-secondary' %>
          -->

        <% end %>

      </div>

      <h5 class="pt-4"><%= t '.map_options' %></h5>

      <%= render partial: 'procedures/map/options' %>

      <%= render partial: 'procedures/map/legend' %>

      <h5 class="pt-4"><%= t '.export' %></h5>

      <div>
        <div class="float-left">
          <%= link_to t('.download_csv'), export_procedures_path(format: :csv), class: 'm-2 btn btn-secondary' %>
        </div>

        <div class="float-left">
          <%= render partial: 'pdf_generator' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade justify-content-center" data-backdrop="static" data-keyboard="false" id="loading-overlay" role="overlay">
  <div class="modal-dialog d-flex h-100 mt-0 mx-auto">
    <div class="spinner-border text-light justify-content-center align-self-center mx-auto" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
</div>

<%= render partial: 'procedures/map/load.js', locals: {
  health_facilities: @health_facilities,
  patients_data: @patients_data,
  cities: @cities,
  census_sectors: @census_sectors,
  regional_health_coordinations: @regional_health_coordinations,
  technical_health_supervisions: @technical_health_supervisions,
  subprefectures: @subprefectures,
  administrative_sectors: @administrative_sectors,
  ubs: @ubs,
  fhs: @fhs,
  census_sectors_counts: @census_sectors_counts,
  dataset_proportion: @dataset_proportion
} %>

app/views/procedures/print.html.erb
<div class="container">
  <div class="map">
    <img src="<%= @base64_map %>">
  </div>

  <div class="information">
    <h1><%= t 'procedures.pdf_generator.title' %></h1>

    <h2><%= t 'procedures.pdf_generator.filters' %></h2>

    <%= render partial: 'shared/services/active_filters', locals: {
      active_filters: @active_filters
    } %>

    <h2 class="pt-4"><%= t 'procedures.pdf_generator.legend' %></h2>

    <p>
      <%= wicked_pdf_image_tag 'ESTADUAL_hf_icon.png' %> <%= t 'procedures.pdf_generator.state' %> <%= wicked_pdf_image_tag 'MUNICIPAL_hf_icon.png' %> <%= t 'procedures.pdf_generator.city' %>
    </p>

    <h2><%= t 'procedures.pdf_generator.source_title' %></h2>

    <p>
      <%= t 'procedures.pdf_generator.source_text' %><br>
      <%= t 'procedures.pdf_generator.source_url' %>
    </p>
  </div>
</div>

app/views/procedures/show.html.erb
<b><%= t('.gender') %></b>: <%= human_attribute_value(@patient_datum, 'gender') %> <br>
<b><%= t('.race') %></b>: <%= human_attribute_value(@patient_datum, 'race') %> <br>
<b><%= t('.age_year') %></b>: <%= @patient_datum.age_year %> <br>
<b><%= t('.educational_level') %></b>: <%= human_attribute_value(@patient_datum, 'educational_level') %> <br>
<b><%= t('.census_sector') %></b>: <%= @patient_datum.census_sector.code %> <br>
<b><%= t('.administrative_sector') %></b>: <%= @patient_datum.administrative_sector.name %> <br>
<b><%= t('.subprefecture') %></b>: <%= @patient_datum.subprefecture.name %> <br>
<b><%= t('.technical_health_supervision') %></b>: <%= @patient_datum.technical_health_supervision.name %> <br>
<b><%= t('.regional_health_coordination') %></b>: <%= @patient_datum.regional_health_coordination.name %> <br>
<b><%= t('.icd_category') %></b>: <%= @hospitalization_datum.icd_category&.description %> <br>
<b><%= t('.admission_date') %></b>: <%= @hospitalization_datum.admission_date %> <br>
<b><%= t('.distance') %></b>: <%= @hospitalization_datum.distance %> <br>
<b><%= t('.health_facility') %></b>: <%= @hospitalization_datum.health_facility.name %>